const initialState = {
    username: '',
    password: '',
    userType: 'Tour Manager',
    firstName: '',
    lastName: '',
    loggedIn: false,
    user: '',
    venue: '',
    venueName: '',
    venueLocation: '',
    artistName: '',
    artistLocation: '',
    artistGenre: ''
};

const LoginReducer = (state = initialState, action) => {
    switch (action.type) {
        case 'ADD_VENUE':
            return {
                user: action.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'ADD_ARTIST':
            return {
                user: action.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'DELETE_ARTIST':
            return {
                user: action.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'ADD_VENUE':
            return {
                user: action.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'DELETE_VENUE':
            return {
                user: action.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'USER_LOADED':
            return {
                user: state.user,
                loggedIn: true,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'LOGOUT':
            return {
                user: '',
                loggedIn: false,
                username: '',
                password: '',
                firstName: '',
                lastName: '',
                userType: 'Tour Manager',
                venue: '',
                venueName: '',
                venueLocation: '',
                artistName: '',
                artistLocation: '',
                artistGenre: ''
            };
        case 'SELECT_VENUE':
            return {
                user: state.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: action.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'CHANGE_USERNAME':
            return {
                user: state.user,
                loggedIn: state.loggedIn,
                username: action.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'CHANGE_PASSWORD':
            return {
                user: state.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: action.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'CHANGE_FIRST_NAME':
            return {
                user: state.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: action.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'CHANGE_LAST_NAME':
            return {
                user: state.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: action.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'CHANGE_USER_TYPE':
            return {
                user: state.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: action.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'CHANGE_VENUE_NAME':
            return {
                user: state.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: action.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'CHANGE_VENUE_LOCATION':
            return {
                user: state.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: action.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'CHANGE_ARTIST_NAME':
            return {
                user: state.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: action.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'CHANGE_ARTIST_LOCATION':
            return {
                user: state.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: action.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'CHANGE_ARTIST_GENRE':
            return {
                user: state.user,
                loggedIn: state.loggedIn,
                username: state.username,
                password: state.password,
                firstName: state.firstName,
                lastName: state.lastName,
                userType: state.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: action.artistGenre
            };
        case 'LOGIN':
            return {
                user: action.user,
                loggedIn: state.loggedIn,
                username: action.user.username,
                password: action.user.password,
                firstName: action.user.firstName,
                lastName: action.user.lastName,
                userType: action.user.userType,
                venue: state.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        case 'REGISTER':
            return {
                user: action.user,
                loggedIn: state.loggedIn,
                username: action.user.username,
                password: action.user.password,
                firstName: action.user.firstName,
                lastName: action.user.lastName,
                userType: action.user.userType,
                venue: action.user.venue,
                venueName: state.venueName,
                venueLocation: state.venueLocation,
                artistName: state.artistName,
                artistLocation: state.artistLocation,
                artistGenre: state.artistGenre
            };
        default:
            return state;
    }
};

export default LoginReducer;
